apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: guestbook-ui
spec:
  replicas: 2
  selector:
    matchLabels:
      app: guestbook-ui
  workloadRef:
    apiVersion: apps/v1
    kind: Deployment
    name: kustomize-guestbook-ui
  minReadySeconds: 30
  progressDeadlineAbort: true
  rollbackWindow:
    revisions: 3
  revisionHistoryLimit: 3
  strategy:
    canary:
      maxSurge: "100%"
      maxUnavailable: 0
      steps:
      - setWeight: 50
      - pause:
          duration: 1m
      # doesn't work like this if pod goes into crashloop
      # query should target the canary pod not the service
      # - analysis:
      #     templates:
      #     - templateName: kustomize-pod-query-analysis
      #     args:
      #     - name: service-name
      #       # hardcoded to "test" should be "stg" staging.
      #       value: kustomize-guestbook-ui.test.svc.cluster.local
