apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: guestbook-ui
spec:
  replicas: 2
  selector:
    matchLabels:
      app: guestbook-ui
  workloadRef:
    apiVersion: apps/v1
    kind: Deployment
    name: kustomize-guestbook-ui
  minReadySeconds: 30
  rollbackWindow:
    revisions: 3
  revisionHistoryLimit: 3
  strategy:
    canary:
      maxSurge: "100%"
      maxUnavailable: 0
      steps:
      - setWeight: 50
      - pause:
          duration: 1m
